"""initial schema

Revision ID: a2605dcc768e
Revises: 
Create Date: 2026-08-13 00:57:20.800154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2605dcc768e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), server_default='open_core', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('drones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('uin', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), server_default='multirotor', nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('firmware', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('gps_status', sa.String(length=20), nullable=False),
    sa.Column('flight_mode', sa.String(length=30), nullable=False),
    sa.Column('armed', sa.Boolean(), nullable=False),
    sa.Column('link_quality', sa.Float(), nullable=False),
    sa.Column('total_flight_hours', sa.Float(), nullable=False),
    sa.Column('battery_cycles', sa.Integer(), nullable=False),
    sa.Column('last_telemetry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gps_status IN ('NO_FIX', '2D_FIX', '3D_FIX', 'GPS_LOST')", name='ck_drones_gps_status'),
    sa.CheckConstraint("status IN ('online', 'offline', 'active', 'maintenance', 'warning', 'critical')", name='ck_drones_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uin')
    )
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.create_index('idx_drones_location', 'drones', ['location'], unique=False, postgresql_using='gist')
    op.create_table('geofences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('altitude_min', sa.Float(), nullable=False),
    sa.Column('altitude_max', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('geofence', 'nfz')", name='ck_geofences_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.create_index('idx_geofences_geometry', 'geofences', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'OPERATOR', 'OBSERVER', 'ANALYST')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('technician', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('flight_hours_at_service', sa.Float(), nullable=False),
    sa.Column('battery_cycles_at_service', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('routine', 'repair', 'upgrade', 'inspection')", name='ck_maintenance_category'),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mission_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aoi_geometry', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mission_type IN ('SAR', 'AGRI', 'INSPECT', 'PATROL', 'SURVEY', 'OTHER')", name='ck_missions_type'),
    sa.CheckConstraint("status IN ('draft', 'planning', 'validating', 'armed', 'active', 'completed', 'aborted')", name='ck_missions_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.create_index('idx_missions_aoi_geometry', 'missions', ['aoi_geometry'], unique=False, postgresql_using='gist')
    op.create_table('payloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('calibrated', 'due', 'uncalibrated', 'fault')", name='ck_payloads_status'),
    sa.CheckConstraint("type IN ('camera', 'thermal', 'lidar', 'multispectral', 'sprayer', 'custom')", name='ck_payloads_type'),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('drone_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'assigned', 'in_progress', 'completed', 'failed')", name='ck_task_bundles_status'),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.create_index('idx_task_bundles_geometry', 'task_bundles', ['geometry'], unique=False, postgresql_using='gist')
    # NOTE: 'spatial_ref_sys' is PostGIS's own system table (owned by the
    # postgis extension) -- autogenerate flags it as "removed" because it
    # isn't one of our declared models, but it must never be dropped here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.drop_index('idx_task_bundles_geometry', table_name='task_bundles', postgresql_using='gist')
    op.drop_table('task_bundles')
    op.drop_table('payloads')
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.drop_index('idx_missions_aoi_geometry', table_name='missions', postgresql_using='gist')
    op.drop_table('missions')
    op.drop_table('maintenance_records')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.drop_index('idx_geofences_geometry', table_name='geofences', postgresql_using='gist')
    op.drop_table('geofences')
    # GeoAlchemy2 auto-creates/drops this GiST index via its Table after_create/before_drop event.
    # op.drop_index('idx_drones_location', table_name='drones', postgresql_using='gist')
    op.drop_table('drones')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
